version: '3.7'

services:
    # PHP-FPM service
    app:
        image: php:8.3-fpm
        container_name: registration_bot
        build: .
        working_dir: /var/www
        dns:
         - 8.8.8.8
         - 8.8.4.4
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        networks:
            - app-network

    # MySQL service
    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: registration_bot
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    # Redis service
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - app-network

    # Laravel Horizon service
    horizon:
        image: php:8.3-fpm
        container_name: laravel_horizon
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: ["php", "artisan", "horizon"]
        depends_on:
            - app
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
